"""estrutura inicial

Revision ID: 9da707016405
Revises: 
Create Date: 2026-10-01 01:19:23.139490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da707016405'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acesso_papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.Boolean(), nullable=False),
    sa.Column('exige_orgao', sa.Boolean(), nullable=False),
    sa.Column('todas', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acesso_papel')),
    sa.UniqueConstraint('codigo', name=op.f('uq_acesso_papel_codigo'))
    )
    op.create_table('coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('solicitada_por', sa.String(length=200), nullable=True),
    sa.Column('total_organizacoes', sa.Integer(), nullable=False),
    sa.Column('total_datasets', sa.Integer(), nullable=False),
    sa.Column('total_recursos', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coleta'))
    )
    op.create_table('ia_perfil_provedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('modelo', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_cifrada', sa.Text(), nullable=True),
    sa.Column('api_key_dica', sa.String(length=20), nullable=True),
    sa.Column('execucao_local', sa.Boolean(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Float(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ia_perfil_provedor')),
    sa.UniqueConstraint('nome', name=op.f('uq_ia_perfil_provedor_nome'))
    )
    op.create_table('ia_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('momento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tarefa', sa.String(length=40), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('perfil_nome', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=200), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('usou_fallback', sa.Boolean(), nullable=False),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_saida', sa.Integer(), nullable=True),
    sa.Column('erro', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ia_uso'))
    )
    with op.batch_alter_table('ia_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ia_uso_momento'), ['momento'], unique=False)

    op.create_table('parametro',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('alterado_por', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chave', name=op.f('pk_parametro'))
    )
    op.create_table('acesso_papel_permissao',
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('permissao', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['acesso_papel.id'], name=op.f('fk_acesso_papel_permissao_papel_id_acesso_papel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('papel_id', 'permissao', name=op.f('pk_acesso_papel_permissao'))
    )
    op.create_table('dataset_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coleta_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coleta.id'], name=op.f('fk_dataset_snapshot_coleta_id_coleta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_snapshot'))
    )
    with op.batch_alter_table('dataset_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_snapshot_coleta_id'), ['coleta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_snapshot_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('ia_vinculo_tarefa',
    sa.Column('tarefa', sa.String(length=40), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('perfil_fallback_id', sa.Integer(), nullable=True),
    sa.Column('alterado_por', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['perfil_fallback_id'], ['ia_perfil_provedor.id'], name=op.f('fk_ia_vinculo_tarefa_perfil_fallback_id_ia_perfil_provedor'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['perfil_id'], ['ia_perfil_provedor.id'], name=op.f('fk_ia_vinculo_tarefa_perfil_id_ia_perfil_provedor'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tarefa', name=op.f('pk_ia_vinculo_tarefa'))
    )
    op.create_table('organizacao',
    sa.Column('ckan_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('sigla', sa.String(length=40), nullable=True),
    sa.Column('ultima_coleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ultima_coleta_id'], ['coleta.id'], name=op.f('fk_organizacao_ultima_coleta_id_coleta')),
    sa.PrimaryKeyConstraint('ckan_id', name=op.f('pk_organizacao'))
    )
    with op.batch_alter_table('organizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizacao_name'), ['name'], unique=False)

    op.create_table('dataset',
    sa.Column('ckan_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('organizacao_id', sa.String(length=64), nullable=True),
    sa.Column('autor', sa.String(length=300), nullable=True),
    sa.Column('autor_email', sa.String(length=300), nullable=True),
    sa.Column('licenca', sa.String(length=100), nullable=True),
    sa.Column('periodicidade_declarada', sa.String(length=100), nullable=True),
    sa.Column('metadata_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=False),
    sa.Column('ativo_no_portal', sa.Boolean(), nullable=False),
    sa.Column('ultima_coleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacao.ckan_id'], name=op.f('fk_dataset_organizacao_id_organizacao')),
    sa.ForeignKeyConstraint(['ultima_coleta_id'], ['coleta.id'], name=op.f('fk_dataset_ultima_coleta_id_coleta')),
    sa.PrimaryKeyConstraint('ckan_id', name=op.f('pk_dataset'))
    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('orgao_id', sa.String(length=64), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['organizacao.ckan_id'], name=op.f('fk_usuario_orgao_id_organizacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('acesso_usuario_papel',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['acesso_papel.id'], name=op.f('fk_acesso_usuario_papel_papel_id_acesso_papel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_acesso_usuario_papel_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'papel_id', name=op.f('pk_acesso_usuario_papel'))
    )
    op.create_table('pda_base_prevista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orgao_sigla', sa.String(length=40), nullable=False),
    sa.Column('nome_previsto', sa.String(length=500), nullable=False),
    sa.Column('prazo_abertura', sa.Date(), nullable=True),
    sa.Column('periodicidade', sa.String(length=40), nullable=True),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.ckan_id'], name=op.f('fk_pda_base_prevista_dataset_id_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pda_base_prevista'))
    )
    with op.batch_alter_table('pda_base_prevista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pda_base_prevista_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pda_base_prevista_orgao_sigla'), ['orgao_sigla'], unique=False)

    op.create_table('recurso',
    sa.Column('ckan_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=True),
    sa.Column('formato', sa.String(length=40), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_type', sa.String(length=20), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datastore_active', sa.Boolean(), nullable=False),
    sa.Column('eh_dicionario_dados', sa.Boolean(), nullable=False),
    sa.Column('ultima_coleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.ckan_id'], name=op.f('fk_recurso_dataset_id_dataset')),
    sa.ForeignKeyConstraint(['ultima_coleta_id'], ['coleta.id'], name=op.f('fk_recurso_ultima_coleta_id_coleta')),
    sa.PrimaryKeyConstraint('ckan_id', name=op.f('pk_recurso'))
    )
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurso_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('lgpd_achado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.String(length=64), nullable=False),
    sa.Column('coluna', sa.String(length=300), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=True),
    sa.Column('ocorrencias', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('confianca', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('impressao_digital', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.ckan_id'], name=op.f('fk_lgpd_achado_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lgpd_achado'))
    )
    with op.batch_alter_table('lgpd_achado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lgpd_achado_impressao_digital'), ['impressao_digital'], unique=False)
        batch_op.create_index(batch_op.f('ix_lgpd_achado_recurso_id'), ['recurso_id'], unique=False)

    op.create_table('lgpd_correcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.String(length=64), nullable=False),
    sa.Column('aprovado_por', sa.String(length=200), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('caminho_backup', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.ckan_id'], name=op.f('fk_lgpd_correcao_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lgpd_correcao'))
    )
    with op.batch_alter_table('lgpd_correcao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lgpd_correcao_recurso_id'), ['recurso_id'], unique=False)

    op.create_table('lgpd_decisao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achado_id', sa.Integer(), nullable=False),
    sa.Column('decisao', sa.String(length=20), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('momento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achado_id'], ['lgpd_achado.id'], name=op.f('fk_lgpd_decisao_achado_id_lgpd_achado')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lgpd_decisao'))
    )
    with op.batch_alter_table('lgpd_decisao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lgpd_decisao_achado_id'), ['achado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lgpd_decisao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lgpd_decisao_achado_id'))

    op.drop_table('lgpd_decisao')
    with op.batch_alter_table('lgpd_correcao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lgpd_correcao_recurso_id'))

    op.drop_table('lgpd_correcao')
    with op.batch_alter_table('lgpd_achado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lgpd_achado_recurso_id'))
        batch_op.drop_index(batch_op.f('ix_lgpd_achado_impressao_digital'))

    op.drop_table('lgpd_achado')
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurso_dataset_id'))

    op.drop_table('recurso')
    with op.batch_alter_table('pda_base_prevista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pda_base_prevista_orgao_sigla'))
        batch_op.drop_index(batch_op.f('ix_pda_base_prevista_dataset_id'))

    op.drop_table('pda_base_prevista')
    op.drop_table('acesso_usuario_papel')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_name'))

    op.drop_table('dataset')
    with op.batch_alter_table('organizacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizacao_name'))

    op.drop_table('organizacao')
    op.drop_table('ia_vinculo_tarefa')
    with op.batch_alter_table('dataset_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_snapshot_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_snapshot_coleta_id'))

    op.drop_table('dataset_snapshot')
    op.drop_table('acesso_papel_permissao')
    op.drop_table('parametro')
    with op.batch_alter_table('ia_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ia_uso_momento'))

    op.drop_table('ia_uso')
    op.drop_table('ia_perfil_provedor')
    op.drop_table('coleta')
    op.drop_table('acesso_papel')
    # ### end Alembic commands ###
